# Generated by Django 4.0.4 on 2022-06-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idAlimento', models.AutoField(primary_key=True, serialize=False)),
                ('nomAlimento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('nomComentario', models.CharField(max_length=30)),
                ('emailComentario', models.CharField(max_length=30)),
                ('Mensaje', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('idDieta', models.AutoField(primary_key=True, serialize=False)),
                ('nomDieta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('idNacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nomNacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('nomReceta', models.CharField(max_length=30)),
                ('ingrediente', models.CharField(max_length=1000)),
                ('preparacion', models.CharField(max_length=2000)),
                ('tiempo', models.IntegerField()),
                ('fotoReceta', models.ImageField(blank='', default='../../static/Recetas/img/Token/foto_default_receta.png', upload_to='foto_receta')),
                ('detalle', models.CharField(default='', max_length=1000)),
                ('Alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.alimento')),
                ('Dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.dieta')),
                ('Nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nomRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomUsuario', models.CharField(max_length=30)),
                ('apellidoCompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank='', default='../../static/Recetas/img/Token/pngwing.com.png', upload_to='foto_perfil')),
                ('contrasena', models.CharField(max_length=20)),
                ('RolUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recetas.rolusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('idValoracion', models.AutoField(primary_key=True, serialize=False)),
                ('mensajeValoracion', models.CharField(max_length=1000)),
                ('estrellaValoracion', models.IntegerField()),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.receta')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.usuario'),
        ),
    ]
