# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NACIONALIDAD',
            fields=[
                ('idNacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nomNacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_USUARIO',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable de tipo de usuario')),
                ('nomTipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomUsuario', models.CharField(max_length=30)),
                ('apellidoCompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto_perfil')),
                ('contrasena', models.CharField(max_length=20)),
                ('TIPO_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RECETA',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('nomReceta', models.CharField(max_length=30)),
                ('ingrediente', models.CharField(max_length=100)),
                ('preparacion', models.CharField(max_length=250)),
                ('fotoReceta', models.ImageField(upload_to='foto_receta')),
                ('NACIONALIDAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.nacionalidad')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.usuario')),
            ],
        ),
    ]
