# Generated by Django 4.0.4 on 2022-06-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('idValoracion', models.AutoField(primary_key=True, serialize=False)),
                ('mensajeValoracion', models.CharField(max_length=1000)),
                ('estrellaValoracion', models.IntegerField()),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.receta')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.usuario')),
            ],
        ),
    ]
