# Generated by Django 4.0.4 on 2022-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TIPO_USUARIO',
            new_name='TipoUsuario',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='NACIONALIDAD',
            new_name='Nacionalidad',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='USUARIO',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='TIPO_USUARIO',
            new_name='TipoUsuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank='', default='foto_perfil/foto_perfil_default', upload_to='foto_perfil'),
        ),
    ]
