# Generated by Django 4.0.4 on 2022-06-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('idFavorito', models.AutoField(primary_key=True, serialize=False)),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.receta')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.usuario')),
            ],
        ),
    ]
