# Generated by Django 4.0.4 on 2022-06-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolusuario',
            old_name='idNacionalidad',
            new_name='idRol',
        ),
        migrations.RenameField(
            model_name='rolusuario',
            old_name='nomNacionalidad',
            new_name='nomRol',
        ),
    ]
