# Generated by Django 4.0.4 on 2022-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0002_rename_tipo_usuario_tipousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('idDificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nomDificultad', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
