# Generated by Django 4.0.4 on 2022-06-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0002_rename_idnacionalidad_rolusuario_idrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='RolUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recetas.rolusuario'),
        ),
    ]
