# Generated by Django 4.0.4 on 2022-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0002_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fotoReceta',
            field=models.ImageField(blank='', default='foto_receta/foto_default_receta.png', upload_to='foto_receta'),
        ),
    ]
