# Generated by Django 4.0.4 on 2022-05-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0003_dificultad_receta_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='Dificultad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Recetas.dificultad'),
            preserve_default=False,
        ),
    ]
