# Generated by Django 4.0.4 on 2022-06-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0003_alter_receta_fotoreceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='detalle',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank='', default='../../static/Recetas/img/Token/pngwing.com.png', upload_to='foto_perfil'),
        ),
    ]
