# Generated by Django 4.0.4 on 2022-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0003_usuario_rolusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank='', default='', upload_to='foto_perfil/<django.db.models.fields.AutoField>jpg'),
        ),
    ]
