# Generated by Django 4.0.4 on 2022-05-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0006_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
