# Generated by Django 4.0.4 on 2022-05-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0007_remove_usuario_tipousuario_delete_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='Dificultad',
        ),
        migrations.DeleteModel(
            name='Dificultad',
        ),
    ]
