# Generated by Django 4.0.4 on 2022-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0008_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('nomComentario', models.CharField(max_length=30)),
                ('emailComentario', models.CharField(max_length=30)),
                ('Mensaje', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank='', default='foto_perfil/foto_perfil_default.png', upload_to='foto_perfil'),
        ),
    ]
