# Generated by Django 4.0.4 on 2022-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0008_remove_receta_dificultad_delete_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingrediente',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.CharField(max_length=2000),
        ),
    ]
