# Generated by Django 4.0.4 on 2022-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0010_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank='', default='foto_perfil/foto_perfil_default.png', upload_to='foto_perfil'),
        ),
    ]
